[package]
name = "liamsnow-com"
version = "0.1.0"
edition = "2024"

[features]
dev = []

[dependencies]
anyhow = "1.0.100"
arc-swap = "1.8.0"
axum = "0.8.8"
brotli = "8.0.2"
clap = { version = "4.5.55", features = ["derive"] }
grass = { version = "0.13.4", features = ["macro"] }
mime_guess = "2.0.5"
notify = "8.2.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full", "process"] }
toml = "0.9.11"
tower-http = { version = "0.6.8", features = ["fs", "trace", "compression-full", "set-header"] }
walkdir = "2.5.0"
