[[routes]]
path = "/"
file = "home.typ"

[[routes]]
path = "/blog"
file = "blog.typ"
nest_dir = "blog"

[[routes]]
path = "/projects"
file = "projects.typ"
nest_dir = "projects"

[[routes]]
path = "/robots.txt"
file = "robots.txt"

[[routes]]
path = "/styles"
auto_nest_dir = "styles"

[[routes]]
path = "/fonts"
auto_nest_dir = "fonts"

