[[routes]]
path = "/opensleep"
file = "opensleep/post.typ"
title = "opensleep 113â˜…"
desc = "Open source firmware for the Eight Sleep Pod 3"
date = "2025-09-04"
homepage = true
highlight = true

[[routes]]
path = "/igloo"
file = "igloo.typ"
title = "igloo"
desc = "A secure, fast, & intuitive smart home platform"
date = "2025-05-06"
homepage = true

[[routes]]
path = "/liamsnow_com"
file = "liamsnow_com/post.typ"
title = "liamsnow.com"
desc = "Fast personal website made in Rust with Axum"
date = "2025-07-04"
homepage = true

[[routes]]
path = "/esphomebridge-rs"
file = "esphomebridge-rs.typ"
title = "esphomebridge-rs"
desc = "ESPHome client API written in Rust"
date = "2025-01-15"
homepage = true

[[routes]]
path = "/ical-rs"
file = "ical-rs.typ"
title = "ical-rs"
desc = "A flexible and typed iCalendar (RFC 5545) library "
date = "2024-11-10"
homepage = true

[[routes]]
path = "/virtex"
file = "virtex/post.typ"
title = "virtex"
desc = "815fps FPGA-based IR machine vision camera"
date = "2022-05-27"
homepage = false


